### PR TITLE
Create .npmignore

### PR DESCRIPTION
**Pull request by thejameskyle**

### CODE REVIEW

**Comment by thlorenz** [comment]
Please show that this makes a meaningful difference, i.e. only if the tarball is significantly smaller will I consider the pull, otherwise not since for some people working offline it is important to access the tests as part of the packages they installed locally on their machine.

You can compare the sizes as follows:

```sh
git checkout master
npm pack
du -h *.tgz

git checkout <your-branch>
npm pack
du -h *.tgz
```

**Comment by thejameskyle** [comment]
On several projects my `node_modules` is 50-100MB more than they need to be, I got this number just my killing all the test directories. Considering how low effort it is to just merge this and run `npm version patch` and `npm publish` I think it's worth everyone just doing it.

**Comment by thlorenz** [comment]
Not much effort to run the script I gave you either to consider if not having tests around is worth the space saved. It's not about the effort to add npmignore which you'll see if you read my initial response more closely.

**Comment by thejameskyle** [comment]
It's non-zero is my point

**Comment by thlorenz** [comment]
non-zero is not enough, please run the script and LMK how big the difference is so I can make a sound decision if I should pull this in or not.

**Comment by jorrit** [comment]
People that want to run the tests should clone the deep-is project, run npm install and get then run the tests. .npmignore is used in situations where deep-is is used as a dependency of some other project. In that case, the tests are not needed and only the files needed for running the code should be present. 

Consider this: you use tape for running the tests, which is a devDependency. When deep-is isn't the main project but a dependency of the current project, its devDependencies will not be downloaded, so the tests can't be run anyway.

The file .npmignore itself should also be added to .npmignore.

A different solution would be to add `"files": ["index.js"]` to package.json.

**Comment by thlorenz** [comment]
> People that want to run the tests should clone the deep-is project

Can't do that if you're offline ;)

**Comment by thlorenz** [comment]
Closing this, please open another one once you provide me with data of how much space we'd actually save ...

**Pull request closed without merging**
